// <auto-generated />
using System;
using GamblingGameWebApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamblingGameWebApi.DataAccess.Migrations
{
    [DbContext(typeof(GamblingGameDbContext))]
    [Migration("20240915122138_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamblingGameWebApi.Entities.Domains.GambleRequests.GambleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InvestPoint")
                        .HasColumnType("int");

                    b.Property<int>("ResultPoints")
                        .HasColumnType("int");

                    b.Property<int>("ResultState")
                        .HasColumnType("int");

                    b.Property<int>("SelectedNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GambleRequests");
                });

            modelBuilder.Entity("GamblingGameWebApi.Entities.Domains.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPoint")
                        .HasColumnType("int");

                    b.Property<int>("InitialPoint")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("baf2c21f-a79e-4cf3-84c8-4d93e69aa6d6"),
                            CurrentPoint = 18,
                            InitialPoint = 12,
                            Name = "Saam"
                        },
                        new
                        {
                            Id = new Guid("0b986f14-eadc-4a32-95b5-2c2649f51412"),
                            CurrentPoint = 0,
                            InitialPoint = 9,
                            Name = "Mouse"
                        });
                });

            modelBuilder.Entity("GamblingGameWebApi.Entities.Domains.GambleRequests.GambleRequest", b =>
                {
                    b.HasOne("GamblingGameWebApi.Entities.Domains.Users.User", "User")
                        .WithMany("Requests")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamblingGameWebApi.Entities.Domains.Users.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
